# Solución de sistemas lineales de ecuaciones algebráicas

## Motivación

Los sistemas lineales de ecuaciones algebráicas son útiles para modelar muchos problemas científicos tales como el balanceo de ecuaciones químicas, el cálculo de corrientes en circuitos electrónicos, además de tener muchísimas aplicaciones dentro de la computación y las mismas matemáticas. Por ello, es de gran utilidad saber cómo se pueden implementar métodos numéricos que resuelvan este tipo de sistemas.

## Sistemas lineales de ecuaciones algebráicas

Un _sistema de ecuaciones_ es un grupo de ecuaciones que deben cumplirse simultáneamente. En general, podemos expresar un sistema de $m$ ecuaciones y $n$ incógnitas como

$$f_1(x_1,x_2,\dots,x_n) = 0,$$

$$f_2(x_1,x_2,\dots,x_n) = 0,$$

$$\vdots$$

$$f_m(x_1,x_2,\dots,x_n) = 0,$$

donde $f_j$ es una función arbitraria, con $1\leq j\leq m$. Una _solución_ al sistema es una $n$-tupla de valores $(x_1,x_2,\dots,x_n)$ para los cuales todas las ecuaciones del sistema se verifican. Un _sistema de ecuaciones algebráicas_ es aquel donde todas las funciones $f_j$ son **polinomios** en las variables $x_1,x_2,\dots,x_n$; más aún, un sistema de este tipo es _lineal_ si en todas las ecuaciones del sistema las incógnitas $x_1,x_2,\dots,x_n$ **no aparecen elevadas a una potencia mayor que uno** y **tampoco aparecen productos entre las diferentes incógnitas**.

En este _notebook_ veremos un método para solucionar sistemas lineales de ecuaciones algebráicas de $n$ ecuaciones y $n$ variables, donde todas las ecuaciones son _linealmente independientes_. En general, este tipo de sistemas se pueden escribir de la siguiente forma (verifica que cumpla las definiciones anteriores):

$$ a_{11}x_1 + a_{12}x_2 + \dots + a_{1n}x_n = b_1, $$

$$ a_{21}x_1 + a_{22}x_2 + \dots + a_{2n}x_n = b_2, $$

$$ \vdots $$

$$ a_{n1}x_1 + a_{n2}x_2 + \dots + a_{nn}x_n = b_n. $$

### Operaciones elementales

Existen tres "operaciones elementales" que le podemos aplicar a este sistema **sin cambiar su conjunto de soluciones**:
1. multiplicar una ecuación (de ambos lados) por una constante no nula;
1. sumarle a una ecuación alguna de las otras ecuaciones multiplicada por una constante arbitraria;
1. intercambiar dos ecuaciones de lugar.

El hecho de que la operación 1 no cambie al conjunto de soluciones del sistema se sigue de que, para todo $1\leq i\leq n$, si $c\neq0$, entonces

$$c(a_{i1}x_1 + a_{i2}x_2 + \dots + a_{in}x_n - b_i) = 0 \iff a_{i1}x_1 + a_{i2}x_2 + \dots + a_{in}x_n - b_i = 0.$$

Similarmente, el hecho de que la operación 2 no cambie al conjunto de soluciones del _sistema_ se sigue de que, para cualesquiera $1\leq i,j\leq n$ y para cualquier constante arbitraria $c'$,

\begin{align}
    (a_{i1}x_1 + a_{i2}x_2 + \dots + a_{in}x_n - b_i) = 0 \ &\land \ (a_{j1}x_1 + a_{j2}x_2 + \dots + a_{jn}x_n - b_j) = 0 \\
    &\iff \\
    (a_{i1}x_1 + a_{i2}x_2 + \dots + a_{in}x_n - b_i) \ &+ \ c'(a_{j1}x_1 + a_{j2}x_2 + \dots + a_{jn}x_n - b_j) = 0.
\end{align}

En efecto: La primera implicación es directa, mientras que la otra se sigue de que las ecuaciones son linealmente dependientes. Por último, es claro por qué la operación 3 no cambia el conjunto de soluciones pues, después de aplicarla, las ecuaciones del sistema siguen siendo las mismas.

## Método de eliminación Gaussiana

A continuación, veremos un algoritmo que aprovecha las operaciones elementales descritas anteriormente para obtener una solución a un sistema lineal de ecuaciones algebráicas.

### Retropropagación

Supongamos que, a través de operaciones elementales, podemos transformar el sistema lineal de ecuaciones algebráicas anterior en uno de la forma

\begin{align*}
    a'_{11}x_1 \ + \ a'_{12}x_2 \ + \dots + \ a'_{1n-1}x_{n-1} \ + \ a'_{1n}x_n &= b'_1, \\
    0 \ + a'_{22}x_2 + \dots + a'_{1n-1}x_{n-1} \ + \ a'_{1n}x_n &= b'_2, \\
    & \ \vdots \\
    0 + 0 + \dots + a'_{n-1,n-1} x_{n-1} + a'_{n-1n}x_n &= b'_{n-1}, \\
    0 \ + \ 0 \ + \ \dots \ + \ \ 0 \ \ + \ \ \ a'_{nn}x_n &= b'_n,
\end{align*}

con $a'_{ii}\neq0$ para $1\leq 1\leq n$ (en la sección **Reducción** explicaremos por qué es posible lograr esto). Observemos que la última ecuación tiene sólo una incógnita, que podemos despejar para obtener

$$x_n = \frac{b'_n}{a'_{nn}}.$$

**Ejercicio** Despeja a $x_{n-1}$ de la penúltima ecuación y sustituye en valor de $x_n$.

$$a'_{n-1,n-1}x_{n-1}+a'_{n-1,n}x_n=b'_{n-1} \iff x_{n-1}=(b'_{n-1}-a'_{n-1,n}x_n)/a'_{n-1,n-1}$$
Como $x_n=b'_{n}/a'_{n,n}$
$$\iff x_{n-1}=(b'_{n-1}-a'_{n-1,n}(b'_{n}/a'_{n,n}))/a'_{n-1,n-1} $$

Iterativamente, por cada ecuación que solucionamos, podemos sustituir todos los valores obtenidos hasta el momento en la ecuación _anterior_ para solucionarla también, hasta haber encontrado valores $(x_1,x_2,\dots,x_n)$ que solucionen todo el sistema. A este procedimiento se le conoce como _retropropagación_.

**Ejercicio** Da una fórmula general para el valor de $x_i$, con $1\leq i<n$, en términos de los $x_j$ para $i < j \leq n$.

$$ a_{ii}x_i + a_{i,i+1}x_{i+1}+ \dots  + a_{in}x_n  = b_i \iff x_i=(b_i -a_{i,i+1}x_{i+1}- \dots  - a_{in}x_n)/a_{ii} $$


**Nota** Lo que nos asegura que los coeficientes $a_{ii}$ con $1\leq i\leq n$ son distintos de cero y, por lo tanto, que nuestras soluciones para $x_n, x_{n-1},\dots,x_1$ están bien definidas es que las ecuaciones del sistema sean linealmente independientes. Esto es equivalente a que la matriz cuadrada tenga un determinante distinto de cero. A este tipo de matrices se les llama _matrices no singulares_.

### Reducción

Al proceso de tomar un sistema lineal de $n$ ecuaciones algebráicas y $n$ incógnitas

$$ a_{11}x_1 + a_{12}x_2 + \dots + a_{1n}x_n = b_1, $$

$$ a_{21}x_1 + a_{22}x_2 + \dots + a_{2n}x_n = b_2, $$

$$ \vdots $$

$$ a_{n1}x_1 + a_{n2}x_2 + \dots + a_{nn}x_n = b_n, $$

y transformarlo a través de operaciones elementales en uno de la forma

\begin{align*}
    a'_{11}x_1 \ + \ a'_{12}x_2 \ + \dots + \ a'_{1n-1}x_{n-1} \ + \ a'_{1n}x_n &= b'_1, \\
    0 \ + a'_{22}x_2 + \dots + a'_{1n-1}x_{n-1} \ + \ a'_{1n}x_n &= b'_2, \\
    & \ \vdots \\
    0 + 0 + \dots + a'_{n-1,n-1} x_{n-1} + a'_{n-1n}x_n &= b'_{n-1}, \\
    0 \ + \ 0 \ + \ \dots \ + \ \ 0 \ \ + \ \ \ a'_{nn}x_n &= b'_n.
\end{align*}

se le conoce como _reducción_, y esto último se conoce como la _forma reducida_ del sistema. Una _transformación elemental_ es la transformación de una ecuación del sistema en otra a través de operaciones elementales.

Sea $E_i$ la $i$-ésima ecuación del sistema no reducido. Si $E_1$ tiene un coeficiente $a_{11}$ distinto de cero, definimos

$$ E_1 =: E'_1; \quad (1) $$

de lo contrario, primero intercambiemos a $E_1$ por alguna ecuación $E_j$ con el coeficiente $a_{j1}$ de $x_1$ distinto de cero

$$E_1 \leftrightarrow E_j$$

y después definimos a $E_1'$ usando la ecuación (1). En ambos casos, redefinamos sus coeficientes como $a'_{11}:= a_{j1}, a'_{12}:= a_{j2},\dots, b'_1:=b_j$, obteniendo la ecuación

$$E'_1: a'_{11}x_1 + a'_{12}x_2 + ... + a'_{1n} x_n = b'_1,$$

con $a'_{11}\neq0$.

Ahora, observemos que, si $E_2$ tiene un coeficiente $a_{22}$ distinto de cero, entonces al aplicar la transformación elemental

$$E_2 \to E_2 - \frac{a_{21}}{a'_{11}} E_1' =: E'_2 \quad (2)$$

la ecuación resultante $E'_2$ tendrá un coeficiente nulo en $x_1$ y no nulo en $x_2$ (Escríbela a mano y verifícalo); en cambio, si $a_{22} = 0$, primero debemos intercambiar a $E_2$ por alguna ecuación $E_k$ con el coeficiente $a_{k2}$ de $x_2$ distinto de cero

$$ E_2 \leftrightarrow E_k $$

y después definir a $E'_2$ con la ecuación (2) para que la ecuación resultante tenga un coeficiente nulo en $x_1$ y no nulo en $x_2$. En ambos casos, definimos a los coeficientes de la ecuación $E'_2$, obteniendo

$$E'_2: a'_{21}x_1 + a'_{22}x_2 + ... + a'_{2n} x_n = b'_2,$$

con $a'_{21}=0$ y $a'_{22}\neq0$.

Luego, si $E_3$ tiene un coeficiente $a_{33}$ distinto de cero, entonces al aplicar la transformación elemental

$$ E_3 \to E_3 - \frac{a_{31}}{a'_{11}} E_1' - \frac{a_{32}}{a'_{22}} E_2' =: E'_3 \quad (3) $$

la ecuación resultante $E'_3$ tendrá coeficientes nulos en $x_1$ y $x_2$, y un coeficiente no nulo en $x_3$; en cambio, si $a_{33} = 0$, primero debemos intercambiar a $E_3$ por alguna ecuación $E_m$ con el coeficiente $a_{l3}$ de $x_3$ distinto de cero

$$ E_3 \leftrightarrow E_l $$

y después definir

y después definir a $E'_3$ con la ecuación (3) para que la ecuación resultante tenga un coeficiente nulo en $x_1$ y $x_2$, y no nulo en $x_3$. En ambos casos, definimos a los coeficientes de la ecuación $E'_3$, obteniendo

$$E'_3: a'_{31}x_1 + a'_{32}x_2 + ... + a'_{3n} x_n = b'_3,$$

con $a'_{31}=a'_{32}=0$ y $a'_{33}\neq0$. (¿Observas un patrón? En serio, es muy importante que escribas al menos estos dos primeros pasos a mano, para que realmente lo _observes_.).

Podemos seguir aplicando el mismo procedimiento iterativamente hasta haber obtenido ecuaciones $E'_1, E'_2, \dots, E'_n$, las cuales forman un sistema _reducido_ al cual le podemos aplicar _retropropagación_.

**Nota** La razón por la que **debe existir** una ecuación $E_j$ con coeficiente $a_{j1}\neq0$ con el cual podamos definir a $E'_1$ y empezar el proceso de reducción es que, de lo contrario, ¡el sistema tendría $n-1$ incógnitas en vez de $n$!

Observemos que las transformaciones elementales **no afectan a las incógnitas** $x_1,x_2\dots,x_n$, sino que **sólo afectan a los coeficientes** $a_{ij}, b_i$, con $1\leq i,j\leq n$. Por lo tanto, podemos hacer reducción _sólo considerando a los coeficientes del sistema_. Similarmente, notemos que, para hacer retropropagación, _sólo necesitamos a los coeficientes del sistema reducido_. Esto nos lleva desechar los sistemas en favor de una representación más sencilla de visualizar y de implementar en código.

### Representación matricial


Consideremos, nuevamente, un sistema lineal de ecuaciones algebráicas

$$ a_{11}x_1 + a_{12}x_2 + \dots + a_{1n}x_n = b_1, $$

$$ a_{21}x_1 + a_{22}x_2 + \dots + a_{2n}x_n = b_2, $$

$$ \vdots $$

$$ a_{n1}x_1 + a_{n2}x_2 + \dots + a_{nn}x_n = b_n. $$

Como tal vez sospeches por la notación de los coeficientes, podemos escribir este sistema como una sola ecuación vectorial

$$ \begin{pmatrix} a_{11} &a_{12} &\dots &a_{1n} \\ a_{21} &a_{22} &\dots &a_{2n} \\ \vdots &\vdots &\ddots &\vdots \\ a_{n1} &a_{n2} &\dots &a_{nn} \end{pmatrix} \begin{pmatrix} x_1 \\ x_2 \\ \vdots \\ x_n \end{pmatrix} = \begin{pmatrix} b_1 \\ b_2 \\ \vdots \\ b_n \end{pmatrix}; $$

o, de forma más sucinta,

$$ A \vec{x} = \vec{b}. $$

Observemos que podemos representar a nuestro sistema de ecuaciones con la matriz aumentada

$$ \big( A\mid\vec{b} \ \big) = \begin{pmatrix} a_{11} &a_{12} &\dots &a_{1n} &\mid &b_1 \\ a_{21} &a_{22} &\dots &a_{2n} &\mid &b_2 \\ \vdots &\vdots &\ddots &\vdots &\mid &\vdots \\ a_{n1} &a_{n2} &\dots &a_{nn} &\mid &b_n \end{pmatrix}. $$

De esta forma, cada renglón de la matriz aumentada representa una ecuación de nuestro sistema... ¡y las operaciones elementales que vimos para sistemas lineales de ecuaciones _coinciden completamente_ con operaciones elementales de matrices! (De hecho, de ahí viene el nombre.) Recordando que las transformaciones elementales sólo afectan a los **coeficientes** de un sistema lineal de ecuaciones, entonces podemos aplicarle **reducción** a la matriz aumentada para llevarla a su forma reducida

$$ \begin{pmatrix} a'_{11} &a'_{12} &\dots &a'_{1n} &\mid &b'_1 \\ 0 &a'_{22} &\dots &a'_{2n} &\mid &b'_2 \\ \vdots &\vdots &\ddots &\vdots &\mid &\vdots \\ 0 &0 &\dots &a'_{nn} &\mid &b'_n \end{pmatrix}. $$

Luego, recordando que la retropropagación se puede llevar a cabo sólo con los coeficientes del sistema reducido, ¡podemos utilizar esta matriz reducida para encontrar la solución de nuestro sistema!

## Implementación

Para este punto, ya debes tener motivación para resolver un problema importante y ubicuo, así como un plan de acción respaldado por una teoría sensata. Ahora sí, ¡te toca implementarlo!

Como sugerencia general, te recomiendo recordar que puedes crear celdas de Jupyter libremente para experimentar con tu código, probarlo con diferentes parámetros, ver si funciona como esperas, e irlo corrigiendo en caso de que no. Además, si así lo deseas, puedes empezar resolviendo sistemas pequeños (por ejemplo, de dos ecuaciones) y, ya que tengas una noción de los procedimientos y cómo implementarlos, generalizar tu código para que también pueda resolver sistemas más grandes. 

**Ejercicio** Crea una función `retropropagación` con un argumento `M`, que puedes suponer que es una matriz aumentada de la forma

$$ \begin{pmatrix} a'_{11} &a'_{12} &\dots &a'_{1n} &\mid &b'_1 \\ 0 &a'_{22} &\dots &a'_{2n} &\mid &b'_2 \\ \vdots &\vdots &\ddots &\vdots &\mid &\vdots \\ 0 &0 &\dots &a'_{nn} &\mid &b'_n \end{pmatrix} $$

-es decir, aquella formada por una matriz triangulada superior y un vector $\vec{b}'$-, que aplique retropropagación a la matriz `M` y devuelva como resultado un arreglo con el vector solución $\vec{x}$.

In [7]:

function retropropagación(A)
n=length(A[:,1]) #Aquí cuento cuantas variables tiene el sistema.
x=zeros(1,n) #Aquí defino un vector donde se guardará el valor de las variables, 
             #no importa los valores de este vector ya que se modificarán, solo importa su dimensión.
for i in n-1:-1:1 #Aquí defino un bucle for para que obtenga primero el valor de x[n] luego de x[n-1] y así sucesivamente hasta x[1].
    x[n]=A[n,n+1]/A[n,n] #Aquí uso el resultado del profesor. 
    sum=0 #Aquí voy a guardar el valor de a_{i,i+1}x_{i+1}+...+ a_{in}x_n.
    for k in i:n-1 #Aquí voy a realizar la suma de a_{i,i+1}x_{i+1}+...+ a_{in}x_n.
        sum=sum+A[i,k+1]*x[k+1]
    end
    
    x[i]=(A[i,n+1]-sum)/A[i,i] #Aquí calculo el valor de x[i] y lo guardo en el vector "x".
end
    return x
end


retropropagación (generic function with 1 method)

In [80]:

B=[ 1 -1 0 0 -6 ; 0 1 1 0 3 ; 0 0 1 2 4; 0 0 0 1 19 ]
  

4×5 Matrix{Int64}:
 1  -1  0  0  -6
 0   1  1  0   3
 0   0  1  2   4
 0   0  0  1  19

In [84]:
retropropagación(B)

1×4 Matrix{Float64}:
 31.0  37.0  -34.0  19.0

Ya hemos implementado un algoritmo capaz de solucionar matrices reducidas. Ahora, implementaremos otro que realice el proceso de reducción de una matriz aumentada. Como este proceso depende de que las entradas que van quedando en la diagonal sean no nulas -para poder dividir entre ellas-, primero implementaremos una función que se asegure de que esto suceda.

**Ejercicio** Crea una función `pivote` que tome tres argumentos `M`, `i` y `j`, y revise si la entrada del renglón `i` y columna `j` de la matriz `M` es igual a cero. En caso que sí lo sea, debe buscar la primera entrada distinta de cero entre los siguientes renglones de la misma columna y, al encontrarla, intercambiar el renglón correspondiente a la entrada no nula con el renglón `i`.

Sugerencias: Recuerda que puedes aplicar la función `length` a un vector columna de una matriz para obtener la cantidad de renglones de esa matriz. Además, puedes crear una variable temporal para no perder información durante el intercambio de los renglones.

In [6]:
function pivote(M,i,j)
if M[i,j] == 0 #Aquí le pregunto si el término M[i,j] es igual a cero, si no es así, no le hace nada a la matriz.
    cont=1
    while M[cont+i,j] == 0 #Aquí reviso cada término de la columna j por debajo de la fila i, para encontar un M[k,j] distinto de cero.
       cont = cont+1 
    end
    Des=M[cont+i, :] #Aquí guardo la fila donde está M[k,j] distinto de cero.
    Ant=M[i,:] #Aquí guardo la fila donde está M[i,j] igual a cero.
    M[i,:]=Des #Aquí los intercambio de lugar
    M[cont+i,:]=Ant
end
end




pivote (generic function with 1 method)

In [289]:
B=[ 0 -1 0 0 -6 ; 0 1 1 0 3 ; 2 0 1 2 4; 0 0 0 1 19 ]


4×5 Matrix{Int64}:
 0  -1  0  0  -6
 0   1  1  0   3
 2   0  1  2   4
 0   0  0  1  19

In [290]:
pivote(B,1,1)
B

4×5 Matrix{Int64}:
 2   0  1  2   4
 0   1  1  0   3
 0  -1  0  0  -6
 0   0  0  1  19

**Ejercicio** Crea una función `reducción` que tome un argumento `M`, que puedes suponer que es una matriz aumentada de la forma

$$ \begin{pmatrix} a_{11} &a_{12} &\dots &a_{1n} &\mid &b_1 \\ a_{21} &a_{22} &\dots &a_{2n} &\mid &b_2 \\ \vdots &\vdots &\ddots &\vdots &\mid &\vdots \\ a_{n1} &a_{n2} &\dots &a_{nn} &\mid &b_n \end{pmatrix} $$

que representa un sistema de ecuaciones algebráicas linealmente independientes -y que, por ende, le podemos aplicar reduccion-, que devuelva la matriz reducida correspondiente.

Sugerencia: Usa la función `pivote` que creaste anteriormente.

In [5]:
function reducción(M)
n=length(M[:,1]) #Aquí calculo cuantas variables tiene el sistema.

if M[1,1]==0 #Aquí verifico si M[1,1] es igual a cero, si es así, que me cambie por otra ecuación con M[k,1] distinto de cero.
    pivote(M,1,1)
end
M[1,:]=M[1,:]*(1/M[1,1]) #Aquí le multiplico 1/M11 al renglón M1 para que en M'11=1 y sea fácil anular el M(k1) de otras ecuaciones.

for i in 2:n #Aquí seleciono un renglón i de la matriz.
    
    for k in i:n #Aquí voy a volver cero cada término por debajo de M(ii).
    M[k,:]=M[k,:]-M[k,i-1]*M[i-1,:] #Como M(i-1,i-1)=1, entonces M'(i,i-1)=M(i,i-1)-M(k,i-1)*M(i-1,i-1)=0.
    end                                                  
    
    if M[i,i]==0 #Aquí verifico si M[i,i] es igual a cero, si es así, que me cambie por otra ecuación con M[k,i] distinto de cero.
    pivote(M,i,i)
    end
    M[i,:]=M[i,:]*(1/M[i,i]) #Aquí le multiplico 1/M(ii) al renglón Mi para volver M'(ii)=1 y sea fácil anular el M(ki) de otras ecuaciones
       
end
    return M
end


reducción (generic function with 1 method)

In [299]:
M=[16.0 -6.0 4.0 1.0 -36.0; 1.0 -8.0 1.0 1.0 -64.0; 16.0 2.0 -4.0 1.0 -4.0; 9.0 8.0 -3.0 1.0 -64.0]

4×5 Matrix{Float64}:
 16.0  -6.0   4.0  1.0  -36.0
  1.0  -8.0   1.0  1.0  -64.0
 16.0   2.0  -4.0  1.0   -4.0
  9.0   8.0  -3.0  1.0  -64.0

In [300]:
reducción(M)

4×5 Matrix{Float64}:
  1.0  -0.375   0.25        0.0625     -2.25
 -0.0   1.0    -0.0983607  -0.122951    8.09836
 -0.0  -0.0     1.0        -0.136364    4.54545
  0.0   0.0     0.0         1.0       -92.0

**Ejercicio** Crea una función `solución` con un argumento `M`, que puedes suponer que es una matriz aumentada que representa un sistema de ecuaciones algebráicas linealmente independientes, que integre las funciones `reducción` y `retropropagación` y devuelva un arreglo con el vector solución $\vec{x}$.

In [21]:
#W=[16.0 -6.0 4.0 1.0 -36.0; 1.0 -8.0 1.0 1.0 -64.0; 16.0 2.0 -4.0 1.0 -4.0; 9.0 8.0 -3.0 1.0 -64.0]
W=[3.0 2.0 6.0; 5.0 10.0 1.0]
#W=[1.0 0.0625 0.0 0.0625 1.0 0.2 ; -1.0 -0.125 0.0 0.125 1.0 0.0 ; 1.0 0.25 0.0 0.25 1.0 1/3; -1.0 -0.5 0.0 0.5 1.0 0.0 ; 1.0 1.0 1.0 1.0 1.0 1.0 ]

2×3 Matrix{Float64}:
 3.0   2.0  6.0
 5.0  10.0  1.0

In [13]:
#Aquí solo redujo la matriz M y luego la evalúo en retropagación para que me devuelva las soluciones del sistema.
function solución(M)
    reducción(M)
    return retropropagación(M)
end

solución (generic function with 1 method)

In [20]:
solución(W)

1×5 Matrix{Float64}:
 0.0777778  0.355556  0.133333  0.355556  0.0777778

## Cálculo de matrices inversas

Una de las características más importantes de las matrices no singulares (esto es, matrices cuadradas con determinante no nulo) es que son invertibles. Es decir que, si $A\in M_{n\times n}(\mathbb{R})$ es tal que $\text{det}(A)\neq 0$, entonces existe $C\in M_{n\times n}(\mathbb{R})$ tal que

$$ AC = I_{n\times n} = CA,$$

donde $I_{n\times n}$ es la matriz identidad con $n$ renglones y $n$ columnas. Observemos que, si esto sucede, entonces de la ecuación $AC = I_{n\times n}$ tenemos que el producto del primer vector columna de $C$ con la matriz $A$ es igual al vector
v
$$ \begin{pmatrix} 1 \\ 0 \\ \vdots \\ 0 \end{pmatrix}. $$

Más generalmente, el producto del $j$-ésimo vector columna de $C$ con la matriz $A$ dará como resultado un vector con $1$ en la $j$-ésima entrada y $0$ en todas las demás.

A raíz de esta observación, podemos armar y solucionar $n$ sistemas lineales de ecuaciones distintos y juntar los vectores solución en una matriz, obteniendo así una matriz _inversa por la derecha_ de $A$. Más aún, se puede ver sencillamente con un poquito de álgebra que esta matriz inversa por la derecha debe ser _la_ inversa. En efecto: sea $A\in M_{n\times n}(\mathbb{R})$ una matriz no singular (invertible), $A^{-1}$ su inversa y $C$ una matriz inversa de $A$ por la derecha; entonces

$$ \begin{align*} C &= I_{n\times n} C \\ &= (A^{-1}A)C  \\ &= A^{-1}(AC) \\ &= A^{-1}I_{n\times n} \\ &= A^{-1}.\end{align*} $$

**Ejercicio** Crea una función `invertir` con un argumento `M`, que puedes suponer que es una matriz cuadrada no singular (invertible), que devuelva la matriz inversa de `M`.

Sugerencia: Utiliza la función `solución` que creaste anteriormente.

### solución
Para hallar la inversa de la matriz $A$, debemos hallar una matriz $B$ tal que $AB=I_{n\times n}$, por lo que al plantear el siguiente sistema de ecuaciones:
$$ AB= \begin{pmatrix} a_{11} &a_{12} &\dots &a_{1n} \\ a_{21} &a_{22} &\dots &a_{2n} \\ \vdots &\vdots &\ddots &\vdots \\ a_{n1} &a_{n2} &\dots &a_{nn} \end{pmatrix} \begin{pmatrix} b_{11} &b_{12} &\dots &b_{1n} \\ b_{21} &b_{22} &\dots &b_{2n} \\ \vdots &\vdots &\ddots &\vdots \\ b_{n1} &b_{n2} &\dots &b_{nn} \end{pmatrix}= \begin{pmatrix} 1 &0 &\dots &0 \\ 0 & 1 &\dots & 0 \\ \vdots &\vdots &\ddots &\vdots \\ 0 & 0 &\dots & 1 \end{pmatrix} $$

Donde los $b_{ij}$ son nuestras incógnitas, y debemos plantear sistema de $n^2$ ecuaciones con $n^2$ variables, por lo que primero obtendremos la matriz ampliada del sistema.

In [402]:
function Matriz_Ec(V) #Esta es la la función que da la matriz ampliada del sistema para obtener la matriz inversa

n=length(V[:,1])*length(V[:,1]) #Aquí calculo cuantas variables tiene el sistema.
n0=length(V[:,1])  #Aquí calculo la dimensión de la matriz que le quiero calcular su inversa.
MP=zeros(n,n+1) #Aquí se guardará la matriz ampliada del sistema de ecuaciones.

function cuenta1n0(i,n0) #Esta es una función que cuenta desde 1,..,n0, ayudará a colocar los coeficientes de la matriz en la matriz ampliada del sistema.
    if (i)%n0 != 0
        return (i)%n0
    else
        return n0
    end
end

cont=1 #Esta es el subindice i que ayudará a colocar los V[i,j] en MP[i,k]
for i in 1:n
    RP=MP[i,:] #Aquí se modificará el renglón i la matriz ampliada del sistema de ecuaciones.
    for k in 0:n0-1
        RP[cuenta1n0(i,n0)+n0*k]=V[cont,k+1] #Aquí se modificará el renglón i la matriz ampliada del sistema de ecuaciones,
                                             #colocando los coeficientes de la matriz V en la matriz ampliada
    end
    MP[i,:]=RP
    
    if i%n0==0
        cont=cont+1
    end 
end

b=MP[:,n+1] #Aqui se reacomodan las entradas de la matriz identidad para que coincidan con los coeficientes de cada ecuación.
for i in 0:n0-1
b[1+i*(n0+1)]=1
end
MP[:,n+1]=b

return MP
end



Matriz_Ec (generic function with 1 method)

In [403]:
#Q=[3 2 4; 5 -1 -3; 4 3 1 ]
Q=[3 5; 1 2]

2×2 Matrix{Int64}:
 3  5
 1  2

In [404]:
Matriz_Ec(Q)

4×5 Matrix{Float64}:
 3.0  0.0  5.0  0.0  1.0
 0.0  3.0  0.0  5.0  0.0
 1.0  0.0  2.0  0.0  0.0
 0.0  1.0  0.0  2.0  1.0

In [395]:
function invertir(V)
n0=length(V[:,1]) #Aquí calculo la dimensión de la matriz que le quiero calcular su inversa.
D=zeros(n0,n0) #Aquí se guardará la matriz inversa
count=0
for i in 1:n0 #Los dos ciclos for se utilizan para reacomodar los coeficientes de la matriz inversa en una matriz de la misma
              #dimensión de la matriz V.   
    for k in 1:n0
        D[i,k]=solución(Matriz_Ec(V))[k+count]  #Aquí se calcula los coeficientes de la matriz inversa.      
    end
count=count+n0
end
return D
end

invertir (generic function with 1 method)

In [401]:
invertir(Q)

2×2 Matrix{Float64}:
  2.0  -5.0
 -1.0   3.0

## El método de propagación

Existe otro método para solucionar sistemas lineales de ecuaciones algebráicas **totalmente análogo al que hemos visto**. En efecto, esto se sigue de observar que, si en vez de tener un sistema cuya matriz asociada sea triangular superior, fuese triangular _inferior_

$$ \begin{pmatrix} a'_{11} &0 &\dots &0 \\ a'_{21} &a'_{22} &\dots &0 \\ \vdots &\vdots &\ddots &\vdots \\ a'_{n1} &a'_{n2} &\dots &a'_{nn} \end{pmatrix} \begin{pmatrix} x_1 \\ x_2 \\ \vdots \\ x_n \end{pmatrix} = \begin{pmatrix} b'_1 \\ b'_2 \\ \vdots \\ b'_n \end{pmatrix} $$

entonces podríamos solucionarlo de principio a fin, obteniendo primero a

$$x_1 = \frac{b'_{1}}{a'_{11}}$$

y luego la fórmula general

$$ x_i = \frac{1}{a'_{ii}} \bigg( b'_i - \sum_{j=1}^{i-1} a'_{ij}x_j \bigg) $$

para $1<i\leq n$. A este método se le conoce como _propagación_, pues solucionamos la primera entrada del vector incógnita y después propagamos esa solución iterativamente hacia adelante. Asimismo, podemos reducir una matriz aumentada de la forma

$$ \begin{pmatrix} a_{11} &a_{12} &\dots &a_{1n} &\mid &b_1 \\ a_{21} &a_{22} &\dots &a_{2n} &\mid &b_2 \\ \vdots &\vdots &\ddots &\vdots &\mid &\vdots \\ a_{n1} &a_{n2} &\dots &a_{nn} &\mid &b_n \end{pmatrix} $$

a una de la forma

$$ \begin{pmatrix} a'_{11} &0 &\dots &0 &\mid &b'_1 \\ a'_{21} &a'_{22} &\dots &0 &\mid &b'_2 \\ \vdots &\vdots &\ddots &\vdots &\mid &\vdots \\ a'_{n1} &a'_{n2} &\dots &a'_{nn} &\mid &b'_n \end{pmatrix} $$

haciendo un proceso inverso al que vimos anteriormente -siempre y cuando, nuevamente, la matriz cuadrada sea no singular.

En inglés, este segundo método (propagación) se conoce como _forward substitution_, mientras que el primero que vimos (retropropagación) se conoce como _backward substitution_.

## Recursos complementarios

* Capítulo 6 "Direct Methods for Solving Linear Systems" de Burden, Faires y Burden, _Numerical Analysis_ (2016).
* Secciones 3.2 "Solution of Triangular Systems" y 3.3 "The Gaussian Elimination Method (GEM) and LU Factorization" de Quarteroni, Sacco y Saleri, _Numerical Mathematics_ (2000).
* Capítulo 2 "Systems of Linear Equations" de Poole, _Linear Algebra: A Modern Introduction_ (2015).